exports.mustLogin=function(req,res,next){
	if(req.session.user){
		next()
	}else{
		req.flash('error','你尚未登录，请登录')
		res.redirect('/users/login')
	}
}
exports.mustNotLogin=function(req,res,next){
	if(req.session.user){
		req.flash('error','你已经登录')
		res.redirect('/')
	}else{
		next()
	}
}
